export type ADD_ITEM = 'ADD_ITEM';
export const ADD_ITEM: ADD_ITEM = 'ADD_ITEM';

export type CANCEL_EDITING = 'CANCEL_EDITING';
export const CANCEL_EDITING: CANCEL_EDITING = 'CANCEL_EDITING';

export type CHANGE_FILTER = 'CHANGE_FILTER';
export const CHANGE_FILTER: CHANGE_FILTER = 'CHANGE_FILTER';

export type CLEAR_COMPLETED = 'CLEAR_COMPLETED';
export const CLEAR_COMPLETED: CLEAR_COMPLETED = 'CLEAR_COMPLETED';

export type CREATING_ITEM = 'CREATING_ITEM';
export const CREATING_ITEM: CREATING_ITEM = 'CREATING_ITEM';

export type DELETE_ITEM = 'DELETE_ITEM';
export const DELETE_ITEM: DELETE_ITEM = 'DELETE_ITEM';

export type DONE_EDITING = 'DONE_EDITING';
export const DONE_EDITING: DONE_EDITING = 'DONE_EDITING';

export type EDIT_ITEM = 'EDIT_ITEM';
export const EDIT_ITEM: EDIT_ITEM = 'EDIT_ITEM';

export type EDITING_NEW = 'EDITING_NEW';
export const EDITING_NEW: EDITING_NEW = 'EDITING_NEW';

export type EDITING_TEXT = 'EDITING_TEXT';
export const EDITING_TEXT: EDITING_TEXT = 'EDITING_TEXT';

export type SET_STATE = 'SET_STATE';
export const SET_STATE: SET_STATE = 'SET_STATE';

export type TOGGLE_COMPLETE = 'TOGGLE_COMPLETE';
export const TOGGLE_COMPLETE: TOGGLE_COMPLETE = 'TOGGLE_COMPLETE';

export type TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const TOGGLE_DRAWER: TOGGLE_DRAWER = 'TOGGLE_DRAWER';
