export type CANCEL_EDITING = 'CANCEL_EDITING';
export const CANCEL_EDITING: CANCEL_EDITING = 'CANCEL_EDITING';

export type CHANGE_FILTER = 'CHANGE_FILTER';
export const CHANGE_FILTER: CHANGE_FILTER = 'CHANGE_FILTER';

export type DONE_EDITING = 'DONE_EDITING';
export const DONE_EDITING: DONE_EDITING = 'DONE_EDITING';

export type EDIT_ITEM = 'EDIT_ITEM';
export const EDIT_ITEM: EDIT_ITEM = 'EDIT_ITEM';

export type EDITING_TEXT = 'EDITING_TEXT';
export const EDITING_TEXT: EDITING_TEXT = 'EDITING_TEXT';

export type SET_STATE = 'SET_STATE';
export const SET_STATE: SET_STATE = 'SET_STATE';

export type TOGGLE_COMPLETE = 'TOGGLE_COMPLETE';
export const TOGGLE_COMPLETE: TOGGLE_COMPLETE = 'TOGGLE_COMPLETE';

export type TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const TOGGLE_DRAWER: TOGGLE_DRAWER = 'TOGGLE_DRAWER';
